spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #仓库地址{application}=spring.application.name: config-server
          uri: https://github.com/jiqfu/{application}
          searchPaths: config
          #用户名
          username: xxx
          #密码
          passphrase: xxx
          #分支
          default-label: master
server:
  port: 8888


